//! Deterministic TOML rendering for generated config fragments.

use std::path::Path;

use crate::{
    core::{AppResult, validate_template, validate_templates},
    generate::model::{GenerateDocument, GeneratedProfile, TomlValue},
};

/// Render generated config to pretty TOML.
pub fn render_document(document: &GenerateDocument) -> AppResult<String> {
    let mut output = String::new();
    output.push_str("# Generated by toven generate.\n");
    output.push_str("# Review before committing; existing config is never overwritten unless --overwrite is used.\n\n");
    output.push_str("[project]\n");
    output.push_str(&format!("schema = {}\n", document.project.schema));
    output.push_str(&format!("name = {}\n", string(&document.project.name)));
    output.push_str(&format!(
        "root = {}\n",
        string(&path(&document.project.root))
    ));
    if let Some(base_ref) = &document.project.base_ref {
        output.push_str(&format!("base_ref = {}\n", string(base_ref)));
    }

    for profile in document.profiles.values() {
        render_profile(&mut output, profile)?;
    }

    Ok(output)
}

fn render_profile(output: &mut String, profile: &GeneratedProfile) -> AppResult<()> {
    validate_templates(
        format!("profiles.{}.module_arg_template", profile.name),
        &profile.module_arg_template,
    )?;
    validate_template(
        format!("profiles.{}.resource_group", profile.name),
        &profile.resource_group,
    )?;

    output.push('\n');
    output.push_str(&format!("[profiles.{}]\n", profile.name));
    output.push_str(&format!("adapter = {}\n", string(profile.adapter.as_str())));
    output.push_str(&format!(
        "execution = {}\n",
        string(&profile.execution.to_string())
    ));
    output.push_str(&format!(
        "module_arg_template = {}\n",
        inline_array(
            &profile
                .module_arg_template
                .iter()
                .map(|value| TomlValue::String(value.clone()))
                .collect::<Vec<_>>()
        )?
    ));
    output.push_str(&format!(
        "resource_group = {}\n",
        string(&profile.resource_group)
    ));

    if !profile.discovery.is_empty() {
        output.push('\n');
        output.push_str(&format!("[profiles.{}.discovery]\n", profile.name));
        for (key, value) in &profile.discovery {
            output.push_str(&format!("{key} = {}\n", value_toml(value)?));
        }
    }

    Ok(())
}

fn value_toml(value: &TomlValue) -> AppResult<String> {
    match value {
        TomlValue::String(value) => Ok(string(value)),
        TomlValue::Array(values) => inline_array(values),
    }
}

fn inline_array(values: &[TomlValue]) -> AppResult<String> {
    if values.is_empty() {
        return Ok("[]".to_string());
    }
    if values.len() <= 2
        && values
            .iter()
            .all(|value| matches!(value, TomlValue::String(_)))
    {
        let values = values
            .iter()
            .map(value_toml)
            .collect::<AppResult<Vec<_>>>()?
            .join(", ");
        return Ok(format!("[{values}]"));
    }

    let mut output = String::from("[\n");
    for value in values {
        output.push_str("  ");
        output.push_str(&value_toml(value)?);
        output.push_str(",\n");
    }
    output.push(']');
    Ok(output)
}

fn string(value: &str) -> String {
    let mut escaped = String::new();
    for character in value.chars() {
        match character {
            '"' => escaped.push_str("\\\""),
            '\\' => escaped.push_str("\\\\"),
            '\u{08}' => escaped.push_str("\\b"),
            '\t' => escaped.push_str("\\t"),
            '\n' => escaped.push_str("\\n"),
            '\u{0C}' => escaped.push_str("\\f"),
            '\r' => escaped.push_str("\\r"),
            character if character.is_control() => {
                let code = u32::from(character);
                if code <= 0xFFFF {
                    escaped.push_str(&format!("\\u{code:04X}"));
                } else {
                    escaped.push_str(&format!("\\U{code:08X}"));
                }
            }
            character => escaped.push(character),
        }
    }
    format!("\"{escaped}\"")
}

fn path(path: &Path) -> String {
    path.components()
        .map(|component| component.as_os_str().to_string_lossy())
        .collect::<Vec<_>>()
        .join("/")
}

pub(crate) fn path_string(path: &Path) -> String {
    let normalized = path
        .components()
        .map(|component| component.as_os_str().to_string_lossy())
        .collect::<Vec<_>>()
        .join("/");
    if normalized.is_empty() {
        ".".to_string()
    } else {
        normalized
    }
}

#[cfg(test)]
mod tests {
    use std::{collections::BTreeMap, path::PathBuf};

    use crate::{
        core::{AdapterId, ExecutionMode},
        generate::model::{GenerateDocument, GeneratedProfile, GeneratedProject, TomlValue},
    };

    use super::{path_string, render_document};

    #[test]
    fn renders_stable_forward_slash_paths() {
        assert_eq!(
            path_string(&PathBuf::from("core").join("Cargo.toml")),
            "core/Cargo.toml"
        );
    }

    #[test]
    fn renders_multiline_manifest_arrays() {
        let mut discovery = BTreeMap::new();
        discovery.insert(
            "manifests".to_string(),
            TomlValue::Array(vec![
                TomlValue::String("core/Cargo.toml".to_string()),
                TomlValue::String("contrib/Cargo.toml".to_string()),
                TomlValue::String("extra/Cargo.toml".to_string()),
            ]),
        );
        let mut profiles = BTreeMap::new();
        profiles.insert(
            "main".to_string(),
            GeneratedProfile {
                name: "main".to_string(),
                adapter: AdapterId::new("rust").expect("adapter id"),
                execution: ExecutionMode::SpawnEach,
                module_arg_template: vec!["-p".to_string(), "{module.package}".to_string()],
                resource_group: "cargo:{project.root}".to_string(),
                discovery,
            },
        );

        let rendered = render_document(&GenerateDocument {
            project: GeneratedProject {
                schema: 1,
                name: "demo".to_string(),
                root: PathBuf::from("."),
                base_ref: None,
            },
            profiles,
            warnings: Vec::new(),
        })
        .expect("render succeeds");

        assert!(rendered.contains("manifests = [\n  \"core/Cargo.toml\",\n"));
    }
}
