//! Deterministic TOML rendering for generated config fragments.

use std::{fmt::Write as _, path::Path};

use crate::{
    core::{
        AppError, AppResult, validate_command_template, validate_identifier,
        validate_shared_inputs, validate_template, validate_templates,
    },
    generate::{
        model::{GenerateDocument, GeneratedProfile, GeneratedTask, TomlValue},
        toml_path,
    },
};

/// Render generated config to pretty TOML.
pub fn render_document(document: &GenerateDocument) -> AppResult<String> {
    let mut output = String::new();
    output.push_str("# Generated by toven generate.\n");
    output.push_str("# Review before committing; existing config is never overwritten unless --overwrite is used.\n\n");
    output.push_str("[project]\n");
    writeln!(output, "schema = {}", document.project.schema).expect("write to string");
    writeln!(output, "name = {}", string(&document.project.name)).expect("write to string");
    writeln!(output, "root = {}", string(&path(&document.project.root))).expect("write to string");
    if let Some(base_ref) = &document.project.base_ref {
        writeln!(output, "base_ref = {}", string(base_ref)).expect("write to string");
    }

    output.push_str("\n[cache]\n");
    writeln!(
        output,
        "location = {}",
        string(match document.cache.location {
            crate::generate::model::GeneratedCacheLocation::User => "user",
            crate::generate::model::GeneratedCacheLocation::Workspace => "workspace",
        })
    )
    .expect("write to string");

    for profile in document.profiles.values() {
        render_profile(&mut output, profile)?;
    }

    Ok(output)
}

fn render_profile(output: &mut String, profile: &GeneratedProfile) -> AppResult<()> {
    validate_identifier(format!("profiles.{}", profile.name), &profile.name)?;
    validate_templates(
        format!("profiles.{}.module_arg_template", profile.name),
        &profile.module_arg_template,
    )?;
    validate_template(
        format!("profiles.{}.resource_group", profile.name),
        &profile.resource_group,
    )?;

    output.push('\n');
    writeln!(output, "[profiles.{}]", profile.name).expect("write to string");
    writeln!(output, "adapter = {}", string(profile.adapter.as_str())).expect("write to string");
    writeln!(
        output,
        "execution = {}",
        string(&profile.execution.to_string())
    )
    .expect("write to string");
    writeln!(
        output,
        "module_arg_template = {}",
        inline_array(
            &profile
                .module_arg_template
                .iter()
                .map(|value| TomlValue::String(value.clone()))
                .collect::<Vec<_>>()
        )?
    )
    .expect("write to string");
    writeln!(
        output,
        "resource_group = {}",
        string(&profile.resource_group)
    )
    .expect("write to string");

    if !profile.discovery.is_empty() {
        output.push('\n');
        writeln!(output, "[profiles.{}.discovery]", profile.name).expect("write to string");
        for (key, value) in &profile.discovery {
            writeln!(output, "{key} = {}", value_toml(value)?).expect("write to string");
        }
    }

    if !profile.tasks.is_empty() {
        output.push('\n');
        writeln!(output, "[profiles.{}.tasks]", profile.name).expect("write to string");
        for (name, task) in &profile.tasks {
            render_task(output, &profile.name, name, task)?;
        }
    }

    Ok(())
}

fn render_task(
    output: &mut String,
    profile_name: &str,
    task_name: &str,
    task: &GeneratedTask,
) -> AppResult<()> {
    let task_field = format!("profiles.{profile_name}.tasks.{task_name}");
    validate_identifier(&task_field, task_name)?;
    validate_command_template(format!("{task_field}.argv"), &task.argv)?;
    validate_shared_inputs(format!("{task_field}.shared_inputs"), &task.shared_inputs)?;
    validate_readiness(&task_field, task)?;

    write!(
        output,
        "{} = {{ argv = {}",
        task_name,
        single_line_array(&task.argv)
    )
    .expect("write to string");
    if task.cache_args {
        output.push_str(", cache_args = true");
    }
    if !task.shared_inputs.is_empty() {
        write!(
            output,
            ", shared_inputs = {}",
            single_line_array(&task.shared_inputs)
        )
        .expect("write to string");
    }
    if task.persistent {
        output.push_str(", persistent = true");
    }
    if let Some(ready_on) = &task.ready_on {
        write!(output, ", ready_on = {}", string(ready_on)).expect("write to string");
    }
    if let Some(ready_command) = &task.ready_command {
        write!(
            output,
            ", ready_command = {}",
            single_line_array(ready_command)
        )
        .expect("write to string");
    }
    if let Some(ready_output) = &task.ready_output {
        write!(output, ", ready_output = {}", string(ready_output)).expect("write to string");
    }
    if let Some(timeout) = task.ready_timeout_seconds {
        write!(output, ", ready_timeout_seconds = {timeout}").expect("write to string");
    }
    output.push_str(" }\n");
    Ok(())
}

fn validate_readiness(task_field: &str, task: &GeneratedTask) -> AppResult<()> {
    let configured = usize::from(task.ready_on.is_some())
        + usize::from(task.ready_command.is_some())
        + usize::from(task.ready_output.is_some());
    if configured > 1 {
        return Err(AppError::invalid_input(
            task_field,
            "persistent readiness must define only one of ready_on, ready_command, or ready_output",
        ));
    }
    if !task.persistent && configured > 0 {
        return Err(AppError::invalid_input(
            task_field,
            "readiness options require persistent = true",
        ));
    }
    if !task.persistent && task.ready_timeout_seconds.is_some() {
        return Err(AppError::invalid_input(
            format!("{task_field}.ready_timeout_seconds"),
            "ready_timeout_seconds requires persistent = true",
        ));
    }
    if let Some(ready_on) = &task.ready_on
        && ready_on != "started"
    {
        return Err(AppError::invalid_input(
            format!("{task_field}.ready_on"),
            "ready_on must be 'started'",
        ));
    }
    if let Some(ready_command) = &task.ready_command {
        validate_command_template(format!("{task_field}.ready_command"), ready_command)?;
    }
    if let Some(ready_output) = &task.ready_output
        && ready_output.is_empty()
    {
        return Err(AppError::invalid_input(
            format!("{task_field}.ready_output"),
            "ready_output cannot be empty",
        ));
    }
    Ok(())
}

fn value_toml(value: &TomlValue) -> AppResult<String> {
    match value {
        TomlValue::String(value) => Ok(string(value)),
        TomlValue::Array(values) => inline_array(values),
    }
}

fn inline_array(values: &[TomlValue]) -> AppResult<String> {
    if values.is_empty() {
        return Ok("[]".to_string());
    }
    if values.len() <= 2
        && values
            .iter()
            .all(|value| matches!(value, TomlValue::String(_)))
    {
        let values = values
            .iter()
            .map(value_toml)
            .collect::<AppResult<Vec<_>>>()?
            .join(", ");
        return Ok(format!("[{values}]"));
    }

    let mut output = String::from("[\n");
    for value in values {
        output.push_str("  ");
        output.push_str(&value_toml(value)?);
        output.push_str(",\n");
    }
    output.push(']');
    Ok(output)
}

fn single_line_array(values: &[String]) -> String {
    let values = values
        .iter()
        .map(|value| string(value))
        .collect::<Vec<_>>()
        .join(", ");
    format!("[{values}]")
}

fn string(value: &str) -> String {
    let mut escaped = String::new();
    for character in value.chars() {
        match character {
            '"' => escaped.push_str("\\\""),
            '\\' => escaped.push_str("\\\\"),
            '\u{08}' => escaped.push_str("\\b"),
            '\t' => escaped.push_str("\\t"),
            '\n' => escaped.push_str("\\n"),
            '\u{0C}' => escaped.push_str("\\f"),
            '\r' => escaped.push_str("\\r"),
            character if character.is_control() => {
                let code = u32::from(character);
                if code <= 0xFFFF {
                    write!(escaped, "\\u{code:04X}").expect("write to string");
                } else {
                    write!(escaped, "\\U{code:08X}").expect("write to string");
                }
            }
            character => escaped.push(character),
        }
    }
    format!("\"{escaped}\"")
}

fn path(path: &Path) -> String {
    toml_path(path)
}

#[cfg(test)]
mod tests {
    use std::{collections::BTreeMap, path::PathBuf};

    use crate::{
        core::{AdapterId, ExecutionMode},
        generate::model::{
            GenerateDocument, GeneratedCache, GeneratedCacheLocation, GeneratedProfile,
            GeneratedProject, GeneratedTask, TomlValue,
        },
    };

    use super::render_document;

    #[test]
    fn renders_multiline_manifest_arrays() {
        let mut discovery = BTreeMap::new();
        discovery.insert(
            "manifests".to_string(),
            TomlValue::Array(vec![
                TomlValue::String("core/Cargo.toml".to_string()),
                TomlValue::String("contrib/Cargo.toml".to_string()),
                TomlValue::String("extra/Cargo.toml".to_string()),
            ]),
        );
        let mut profiles = BTreeMap::new();
        profiles.insert(
            "main".to_string(),
            GeneratedProfile {
                name: "main".to_string(),
                adapter: AdapterId::new("rust").expect("adapter id"),
                execution: ExecutionMode::SpawnEach,
                module_arg_template: vec!["-p".to_string(), "{module.package}".to_string()],
                resource_group: "cargo:{project.root}".to_string(),
                tasks: BTreeMap::new(),
                discovery,
            },
        );

        let rendered = render_document(&GenerateDocument {
            project: GeneratedProject {
                schema: 1,
                name: "demo".to_string(),
                root: PathBuf::from("."),
                base_ref: None,
            },
            cache: GeneratedCache {
                location: GeneratedCacheLocation::User,
            },
            profiles,
            warnings: Vec::new(),
        })
        .expect("render succeeds");

        assert!(rendered.contains("manifests = [\n  \"core/Cargo.toml\",\n"));
    }

    #[test]
    fn rejects_invalid_profile_names() {
        let mut profiles = BTreeMap::new();
        profiles.insert(
            "bad/name".to_string(),
            GeneratedProfile {
                name: "bad/name".to_string(),
                adapter: AdapterId::new("rust").expect("adapter id"),
                execution: ExecutionMode::SpawnEach,
                module_arg_template: vec!["-p".to_string(), "{module.package}".to_string()],
                resource_group: "cargo:{project.root}".to_string(),
                tasks: BTreeMap::new(),
                discovery: BTreeMap::new(),
            },
        );

        let error = render_document(&GenerateDocument {
            project: GeneratedProject {
                schema: 1,
                name: "demo".to_string(),
                root: PathBuf::from("."),
                base_ref: None,
            },
            cache: GeneratedCache {
                location: GeneratedCacheLocation::User,
            },
            profiles,
            warnings: Vec::new(),
        })
        .expect_err("invalid profile name fails");

        assert!(error.message.contains("profiles.bad/name"));
    }

    #[test]
    fn renders_generated_tasks_as_inline_tables() {
        let mut tasks = BTreeMap::new();
        tasks.insert(
            "check".to_string(),
            GeneratedTask {
                argv: vec![
                    "cargo".to_string(),
                    "check".to_string(),
                    "--manifest-path".to_string(),
                    "{module.manifest}".to_string(),
                    "{module.args}".to_string(),
                    "{args}".to_string(),
                ],
                cache_args: false,
                shared_inputs: vec!["Cargo.lock".to_string()],
                persistent: false,
                ready_on: None,
                ready_command: None,
                ready_output: None,
                ready_timeout_seconds: None,
            },
        );
        let mut profiles = BTreeMap::new();
        profiles.insert(
            "main".to_string(),
            GeneratedProfile {
                name: "main".to_string(),
                adapter: AdapterId::new("rust").expect("adapter id"),
                execution: ExecutionMode::SpawnEach,
                module_arg_template: vec!["-p".to_string(), "{module.package}".to_string()],
                resource_group: "cargo:{project.root}".to_string(),
                tasks,
                discovery: BTreeMap::new(),
            },
        );

        let document = GenerateDocument {
            project: GeneratedProject {
                schema: 1,
                name: "demo".to_string(),
                root: PathBuf::from("."),
                base_ref: None,
            },
            cache: GeneratedCache {
                location: GeneratedCacheLocation::User,
            },
            profiles,
            warnings: Vec::new(),
        };
        let first = render_document(&document).expect("render succeeds");
        let second = render_document(&document).expect("render is stable");

        assert_eq!(first, second);
        assert!(first.contains(
            "check = { argv = [\"cargo\", \"check\", \"--manifest-path\", \"{module.manifest}\", \"{module.args}\", \"{args}\"], shared_inputs = [\"Cargo.lock\"] }"
        ));
        assert!(first.contains("[cache]\nlocation = \"user\""));
    }
}
